

version: '3.8'

networks:
  visitor-network:
    driver: bridge

services:

  backend:
    build: ./sugmya-visitor.api
    container_name: visitor-backend
    restart: always
    networks:
      - visitor-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: visitor-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./sugmya-visitor.ui/dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - backend
    networks:
      - visitor-network

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: visitor-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    entrypoint: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot --quiet;
      nginx -s reload;
      sleep 12h & wait $${!};
      done"
