version: '3.8'

networks:
  visitor-network:
    driver: bridge

services:

  backend:
    image: 908103136691.dkr.ecr.ap-south-1.amazonaws.com/visitor-backend
    container_name: visitor-backend
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - visitor-network

  frontend:
    image: 908103136691.dkr.ecr.ap-south-1.amazonaws.com/visitor-frontend
    container_name: visitor-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - visitor-network

  nginx:
    image: nginx:alpine
    container_name: visitor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - visitor-network

  certbot:
    image: certbot/certbot
    container_name: visitor-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - visitor-network

