
networks:
  visitor-network:
    driver: bridge

services:

  # ---------------- BACKEND (.NET) ----------------
  backend:
    image: 908103136691.dkr.ecr.ap-south-1.amazonaws.com/visitor-backend
    container_name: visitor-backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://backend:8080
    expose:
      - "8080"
    networks:
      - visitor-network

  # ---------------- FRONTEND (Nginx + Angular) ----------------
  frontend:
    image: 908103136691.dkr.ecr.ap-south-1.amazonaws.com/visitor-frontend
    container_name: visitor-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - visitor-network
